from sklearn.model_selection import train_test_split

from dataset.time_varying_generator import (
    TimeVaryingQECDatasetGenerator
)

from decoders.time_varying_ml import (
    TimeVaryingLogisticDecoder,
    TimeVaryingRandomForestDecoder,
    TimeVaryingMLPDecoder
)

from experiments.quantum_ai_decoder_integration import (
    QuantumAIDecoderIntegration
)


ROUNDS = 5
PHYSICAL_ERROR_PROBABILITY = 0.10
MEASUREMENT_NOISE_PROBABILITY = 0.10

TRAINING_SAMPLES = 3000
TEST_SAMPLES = 100

RANDOM_SEED = 42


# =========================================================
# DETECTION EVENTS
# =========================================================

def calculate_detection_events(
    syndrome_history
):
    detection_events = []

    previous_syndrome = "00"

    for syndrome in syndrome_history:

        event_s1 = (
            int(previous_syndrome[0])
            ^ int(syndrome[0])
        )

        event_s2 = (
            int(previous_syndrome[1])
            ^ int(syndrome[1])
        )

        detection_events.append(
            f"{event_s1}{event_s2}"
        )

        previous_syndrome = syndrome

    return detection_events


# =========================================================
# FEATURE ENCODING
# =========================================================

def encode_features(
    syndrome_history,
    detection_events
):
    features = []

    # -----------------------------------------------------
    # Observed syndrome history
    # -----------------------------------------------------

    for syndrome in syndrome_history:

        features.extend(
            int(bit)
            for bit in syndrome
        )

    # -----------------------------------------------------
    # Detection events
    # -----------------------------------------------------

    for event in detection_events:

        features.extend(
            int(bit)
            for bit in event
        )

    return features


# =========================================================
# CREATE AI TRAINING DATA
# =========================================================

def create_training_data(
    samples
):
    X = []
    y = []

    for sample in samples:

        # -------------------------------------------------
        # IMPORTANT
        #
        # Use OBSERVED syndrome history.
        #
        # The observed syndrome already contains
        # measurement noise generated by the dataset
        # generator.
        #
        # Do NOT use perfect syndrome_history here.
        # -------------------------------------------------

        observed_syndrome_history = sample[
            "observed_syndrome_history"
        ]

        detection_events = sample[
            "detection_events"
        ]

        features = encode_features(
            observed_syndrome_history,
            detection_events
        )

        target = sample[
            "final_error_state"
        ]

        X.append(features)
        y.append(target)

    return X, y


# =========================================================
# TRAIN DECODER
# =========================================================

def train_decoder(
    decoder,
    X_train,
    y_train
):
    decoder.train(
        X_train,
        y_train
    )

    return decoder


# =========================================================
# RUN ONE DECODER TEST
# =========================================================

def run_decoder_test(
    name,
    decoder,
    X_train,
    y_train,
    test_samples
):

    print()
    print("===================================")
    print(f" {name}")
    print("===================================")

    print(
        f"Training samples : {len(X_train)}"
    )

    print(
        f"Input features   : {len(X_train[0])}"
    )

    print(
        f"Target size      : {len(y_train[0])}"
    )

    # -----------------------------------------------------
    # AI TRAINING
    # -----------------------------------------------------

    train_decoder(
        decoder,
        X_train,
        y_train
    )

    print(
        "AI training      : PASS"
    )

    # -----------------------------------------------------
    # Quantum + AI integration
    #
    # Measurement noise is now enabled.
    # -----------------------------------------------------

    integration = QuantumAIDecoderIntegration(
        rounds=ROUNDS,
        shots=1,
        measurement_noise_probability=(
            MEASUREMENT_NOISE_PROBABILITY
        ),
        random_seed=RANDOM_SEED
    )

    results = integration.run_experiment(
        samples=test_samples,
        decoder=decoder
    )

    metrics = integration.calculate_metrics(
        results
    )

    print(
        "Quantum + AI     : PASS"
    )

    print()

    print(
        f"Trials           : "
        f"{metrics['total_trials']}"
    )

    print(
        f"Physical success : "
        f"{metrics['physical_success_rate']:.4f}"
    )

    print(
        f"Logical success  : "
        f"{metrics['logical_success_rate']:.4f}"
    )

    print(
        f"Logical error    : "
        f"{metrics['logical_error_rate']:.4f}"
    )

    # -----------------------------------------------------
    # EXAMPLE TRIAL
    # -----------------------------------------------------

    example = results[0]

    print()
    print(
        "Example Quantum → AI Trial"
    )

    print(
        f"Logical state    : "
        f"{example['logical_state']}"
    )

    print(
        f"Perfect syndrome : "
        f"{example['perfect_syndrome_history']}"
    )

    print(
        f"Observed syndrome: "
        f"{example['observed_syndrome_history']}"
    )

    print(
        f"Detection events : "
        f"{example['detection_events']}"
    )

    print(
        f"AI features      : "
        f"{example['features']}"
    )

    print(
        f"Actual error     : "
        f"{example['actual_error']}"
    )

    print(
        f"AI prediction    : "
        f"{example['predicted_error']}"
    )

    print(
        f"Measured state   : "
        f"{example['measured_state']}"
    )

    print(
        f"Recovered logical: "
        f"{example['recovered_logical']}"
    )

    print(
        f"Physical success : "
        f"{example['physical_success']}"
    )

    print(
        f"Logical success  : "
        f"{example['logical_success']}"
    )

    return metrics


# =========================================================
# MAIN
# =========================================================

def main():

    print()
    print("===================================")
    print(" QUANTUM + AI QEC")
    print(" MEASUREMENT NOISE TEST")
    print("===================================")

    print()
    print(
        f"Rounds                    : {ROUNDS}"
    )

    print(
        f"Physical error probability: "
        f"{PHYSICAL_ERROR_PROBABILITY}"
    )

    print(
        f"Measurement noise         : "
        f"{MEASUREMENT_NOISE_PROBABILITY}"
    )

    print(
        f"Training samples          : "
        f"{TRAINING_SAMPLES}"
    )

    print(
        f"Test samples              : "
        f"{TEST_SAMPLES}"
    )

    # =====================================================
    # TRAINING DATA
    # =====================================================

    print()
    print(
        "Generating training dataset..."
    )

    training_generator = (
        TimeVaryingQECDatasetGenerator(
            rounds=ROUNDS,
            physical_error_probability=(
                PHYSICAL_ERROR_PROBABILITY
            ),
            measurement_noise_probability=(
                MEASUREMENT_NOISE_PROBABILITY
            ),
            seed=RANDOM_SEED
        )
    )

    training_samples = (
        training_generator.generate_dataset(
            TRAINING_SAMPLES
        )
    )

    # =====================================================
    # CREATE TRAINING FEATURES
    # =====================================================

    X, y = create_training_data(
        training_samples
    )

    print(
        f"Training feature count : "
        f"{len(X[0])}"
    )

    print(
        f"Training target size   : "
        f"{len(y[0])}"
    )

    # =====================================================
    # TRAIN / VALIDATION SPLIT
    #
    # For this integration test we only need
    # a training set and a completely independent
    # quantum test dataset.
    # =====================================================

    X_train, _, y_train, _ = train_test_split(
        X,
        y,
        test_size=0.10,
        random_state=RANDOM_SEED
    )

    # =====================================================
    # TEST DATA
    # =====================================================

    print()
    print(
        "Generating independent test dataset..."
    )

    test_generator = (
        TimeVaryingQECDatasetGenerator(
            rounds=ROUNDS,
            physical_error_probability=(
                PHYSICAL_ERROR_PROBABILITY
            ),
            measurement_noise_probability=(
                MEASUREMENT_NOISE_PROBABILITY
            ),
            seed=123
        )
    )

    test_samples = (
        test_generator.generate_dataset(
            TEST_SAMPLES
        )
    )

    # =====================================================
    # LOGISTIC REGRESSION
    # =====================================================

    run_decoder_test(
        "LOGISTIC REGRESSION",
        TimeVaryingLogisticDecoder(
            random_state=RANDOM_SEED
        ),
        X_train,
        y_train,
        test_samples
    )

    # =====================================================
    # RANDOM FOREST
    # =====================================================

    run_decoder_test(
        "RANDOM FOREST",
        TimeVaryingRandomForestDecoder(
            n_estimators=100,
            random_state=RANDOM_SEED
        ),
        X_train,
        y_train,
        test_samples
    )

    # =====================================================
    # MLP
    # =====================================================

    run_decoder_test(
        "MLP",
        TimeVaryingMLPDecoder(
            hidden_layer_sizes=(32, 16),
            max_iter=1000,
            random_state=RANDOM_SEED
        ),
        X_train,
        y_train,
        test_samples
    )

    # =====================================================
    # FINAL RESULT
    # =====================================================

    print()
    print("===================================")
    print(" FINAL RESULT")
    print("===================================")

    print(
        "Quantum syndrome → measurement noise"
    )

    print(
        "→ AI → quantum correction"
    )

    print(
        "MEASUREMENT NOISE TEST : SUCCESS"
    )


if __name__ == "__main__":
    main()